// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * WorkMate Task Manager API
 *
 * API для управления длительными I/O задачами
 *
 * API version: 1.0.0
 * Contact: support@example.com
 */

package openapi

import (
	"context"
	"net/http"
)



// TasksAPIRouter defines the required methods for binding the api requests to a responses for the TasksAPI
// The TasksAPIRouter implementation should parse necessary information from the http request,
// pass the data to a TasksAPIServicer to perform the required actions, then write the service results to the http response.
type TasksAPIRouter interface { 
	GetTasks(http.ResponseWriter, *http.Request)
	CreateTask(http.ResponseWriter, *http.Request)
	GetTask(http.ResponseWriter, *http.Request)
	DeleteTask(http.ResponseWriter, *http.Request)
	GetTaskResult(http.ResponseWriter, *http.Request)
}


// TasksAPIServicer defines the api actions for the TasksAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type TasksAPIServicer interface { 
	GetTasks(context.Context) (ImplResponse, error)
	CreateTask(context.Context, CreateTaskRequest) (ImplResponse, error)
	GetTask(context.Context, string) (ImplResponse, error)
	DeleteTask(context.Context, string) (ImplResponse, error)
	GetTaskResult(context.Context, string) (ImplResponse, error)
}
