// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * WorkMate Task Manager API
 *
 * API для управления длительными I/O задачами
 *
 * API version: 1.0.0
 * Contact: support@example.com
 */

package openapi




type TaskListResponse struct {

	Tasks []Task `json:"tasks"`
}

// AssertTaskListResponseRequired checks if the required fields are not zero-ed
func AssertTaskListResponseRequired(obj TaskListResponse) error {
	elements := map[string]interface{}{
		"tasks": obj.Tasks,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Tasks {
		if err := AssertTaskRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTaskListResponseConstraints checks if the values respects the defined constraints
func AssertTaskListResponseConstraints(obj TaskListResponse) error {
	for _, el := range obj.Tasks {
		if err := AssertTaskConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
