// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * WorkMate Task Manager API
 *
 * API для управления длительными I/O задачами
 *
 * API version: 1.0.0
 * Contact: support@example.com
 */

package openapi




type CreateTaskRequest struct {

	// Название задачи
	Name string `json:"name"`
}

// AssertCreateTaskRequestRequired checks if the required fields are not zero-ed
func AssertCreateTaskRequestRequired(obj CreateTaskRequest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateTaskRequestConstraints checks if the values respects the defined constraints
func AssertCreateTaskRequestConstraints(obj CreateTaskRequest) error {
	return nil
}
