// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * WorkMate Task Manager API
 *
 * API для управления длительными I/O задачами
 *
 * API version: 1.0.0
 * Contact: support@example.com
 */

package openapi


import (
	"time"
)



type Task struct {

	// Уникальный идентификатор задачи
	Id string `json:"id"`

	// Текущий статус задачи
	Status string `json:"status"`

	// Время создания задачи
	CreatedAt time.Time `json:"createdAt"`

	// Время начала выполнения задачи
	StartedAt time.Time `json:"startedAt,omitempty"`

	// Время завершения задачи
	FinishedAt time.Time `json:"finishedAt,omitempty"`

	// Результат выполнения задачи (только для завершенных задач)
	Result string `json:"result,omitempty"`

	// Описание ошибки (только для неудачных задач)
	Error string `json:"error,omitempty"`

	// Продолжительность выполнения задачи
	Duration string `json:"duration,omitempty"`
}

// AssertTaskRequired checks if the required fields are not zero-ed
func AssertTaskRequired(obj Task) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"status": obj.Status,
		"createdAt": obj.CreatedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTaskConstraints checks if the values respects the defined constraints
func AssertTaskConstraints(obj Task) error {
	return nil
}
