// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * WorkMate Task Manager API
 *
 * API для управления длительными I/O задачами
 *
 * API version: 1.0.0
 * Contact: support@example.com
 */

package openapi




type TaskResponse struct {

	Task Task `json:"task"`
}

// AssertTaskResponseRequired checks if the required fields are not zero-ed
func AssertTaskResponseRequired(obj TaskResponse) error {
	elements := map[string]interface{}{
		"task": obj.Task,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertTaskRequired(obj.Task); err != nil {
		return err
	}
	return nil
}

// AssertTaskResponseConstraints checks if the values respects the defined constraints
func AssertTaskResponseConstraints(obj TaskResponse) error {
	if err := AssertTaskConstraints(obj.Task); err != nil {
		return err
	}
	return nil
}
